"""
Configuration module for NHL Stats Dashboard.
Contains the list of relevant statistics for each position and team-color mapping.
"""

# Select relevant stats for each position
skater_stats= [
    'games_played','icetime','shifts','gameScore','onIce_xGoalsPercentage','offIce_xGoalsPercentage',
    'onIce_corsiPercentage','offIce_corsiPercentage','onIce_fenwickPercentage','offIce_fenwickPercentage',
    'iceTimeRank','I_F_xOnGoal','I_F_xGoals','I_F_xRebounds','I_F_xFreeze','I_F_xPlayStopped',
    'I_F_xPlayContinuedInZone','I_F_xPlayContinuedOutsideZone','I_F_flurryAdjustedxGoals',
    'I_F_scoreVenueAdjustedxGoals','I_F_flurryScoreVenueAdjustedxGoals','I_F_primaryAssists',
    'I_F_secondaryAssists','I_F_shotsOnGoal','I_F_missedShots','I_F_blockedShotAttempts',
    'I_F_shotAttempts','I_F_points','I_F_goals','I_F_rebounds','I_F_reboundGoals','I_F_freeze',
    'I_F_playStopped','I_F_playContinuedInZone','I_F_playContinuedOutsideZone','I_F_savedShotsOnGoal',
    'I_F_savedUnblockedShotAttempts','penalties','I_F_penalityMinutes','I_F_faceOffsWon', 'I_F_hits',
    'I_F_takeaways','I_F_giveaways','I_F_lowDangerShots','I_F_mediumDangerShots','I_F_highDangerShots',
    'I_F_lowDangerxGoals','I_F_mediumDangerxGoals','I_F_highDangerxGoals','I_F_lowDangerGoals',
    'I_F_mediumDangerGoals','I_F_highDangerGoals','I_F_scoreAdjustedShotsAttempts','I_F_unblockedShotAttempts',
    'I_F_scoreAdjustedUnblockedShotAttempts','I_F_dZoneGiveaways','I_F_xGoalsFromxReboundsOfShots',
    'I_F_xGoalsFromActualReboundsOfShots','I_F_reboundxGoals','I_F_xGoals_with_earned_rebounds',
    'I_F_xGoals_with_earned_rebounds_scoreAdjusted','I_F_xGoals_with_earned_rebounds_scoreFlurryAdjusted',
    'I_F_shifts','I_F_oZoneShiftStarts','I_F_dZoneShiftStarts','I_F_neutralZoneShiftStarts','I_F_flyShiftStarts',
    'I_F_oZoneShiftEnds','I_F_dZoneShiftEnds','I_F_neutralZoneShiftEnds','I_F_flyShiftEnds','faceoffsWon',
    'faceoffsLost','timeOnBench','penalityMinutes','penalityMinutesDrawn','penaltiesDrawn','shotsBlockedByPlayer',
    'OnIce_F_xOnGoal','OnIce_F_xGoals','OnIce_F_flurryAdjustedxGoals','OnIce_F_scoreVenueAdjustedxGoals',
    'OnIce_F_flurryScoreVenueAdjustedxGoals','OnIce_F_shotsOnGoal','OnIce_F_missedShots','OnIce_F_blockedShotAttempts','OnIce_F_shotAttempts',
    'OnIce_F_goals','OnIce_F_rebounds','OnIce_F_reboundGoals','OnIce_F_lowDangerShots','OnIce_F_mediumDangerShots',
    'OnIce_F_highDangerShots','OnIce_F_lowDangerxGoals','OnIce_F_mediumDangerxGoals','OnIce_F_highDangerxGoals',
    'OnIce_F_lowDangerGoals','OnIce_F_mediumDangerGoals','OnIce_F_highDangerGoals','OnIce_F_scoreAdjustedShotsAttempts',
    'OnIce_F_unblockedShotAttempts','OnIce_F_scoreAdjustedUnblockedShotAttempts','OnIce_F_xGoalsFromxReboundsOfShots',
    'OnIce_F_xGoalsFromActualReboundsOfShots','OnIce_F_reboundxGoals','OnIce_F_xGoals_with_earned_rebounds',
    'OnIce_F_xGoals_with_earned_rebounds_scoreAdjusted','OnIce_F_xGoals_with_earned_rebounds_scoreFlurryAdjusted',
    'OnIce_A_xOnGoal','OnIce_A_xGoals','OnIce_A_flurryAdjustedxGoals','OnIce_A_scoreVenueAdjustedxGoals',
    'OnIce_A_flurryScoreVenueAdjustedxGoals','OnIce_A_shotsOnGoal','OnIce_A_missedShots','OnIce_A_blockedShotAttempts',
    'OnIce_A_shotAttempts','OnIce_A_goals','OnIce_A_rebounds','OnIce_A_reboundGoals','OnIce_A_lowDangerShots',
    'OnIce_A_mediumDangerShots','OnIce_A_highDangerShots','OnIce_A_lowDangerxGoals','OnIce_A_mediumDangerxGoals',
    'OnIce_A_highDangerxGoals','OnIce_A_lowDangerGoals','OnIce_A_mediumDangerGoals','OnIce_A_highDangerGoals',
    'OnIce_A_scoreAdjustedShotsAttempts','OnIce_A_unblockedShotAttempts','OnIce_A_scoreAdjustedUnblockedShotAttempts',
    'OnIce_A_xGoalsFromxReboundsOfShots','OnIce_A_xGoalsFromActualReboundsOfShots','OnIce_A_reboundxGoals',
    'OnIce_A_xGoals_with_earned_rebounds','OnIce_A_xGoals_with_earned_rebounds_scoreAdjusted',
    'OnIce_A_xGoals_with_earned_rebounds_scoreFlurryAdjusted','OffIce_F_xGoals','OffIce_A_xGoals','OffIce_F_shotAttempts',
    'OffIce_A_shotAttempts','xGoalsForAfterShifts','xGoalsAgainstAfterShifts','corsiForAfterShifts','corsiAgainstAfterShifts',
    'fenwickForAfterShifts','fenwickAgainstAfterShifts'
]

stats_map = {
    'games_played': 'Games Played',
    'icetime': 'Icetime (min)',
    'shifts': 'Shifts',
    'gameScore': 'Game Score',
    'onIce_xGoalsPercentage': 'xGoals Percentage - On Ice',
    'offIce_xGoalsPercentage': 'xGoals Percentage - Off Ice',
    'onIce_corsiPercentage': 'Corsi Percentage - On Ice',
    'offIce_corsiPercentage': 'Corsi Percentage - Off Ice',
    'onIce_fenwickPercentage': 'Fenwick Percentage - On Ice',
    'offIce_fenwickPercentage': 'Fenwick Percentage - Off Ice',
    'iceTimeRank': 'Ice Time Rank',
    'I_F_xOnGoal': 'xGoals - On Ice',
    'I_F_xGoals': 'xGoals',
    'I_F_xRebounds': 'xRebounds',
    'I_F_xFreeze': 'xFreezes',
    'I_F_xPlayStopped': 'xPlay Stopped',
    'I_F_xPlayContinuedInZone': 'xPlay Continued In Zone',
    'I_F_xPlayContinuedOutsideZone': 'xPlay Continued Outside Zone',
    'I_F_flurryAdjustedxGoals': 'xGoals - Flurry Adjusted',
    'I_F_scoreVenueAdjustedxGoals': 'xGoals - Score Venue Adjusted',
    'I_F_flurryScoreVenueAdjustedxGoals': 'xGoals - Flurry + Score Venue Adjusted',
    'I_F_primaryAssists': 'Primary Assists',
    'I_F_secondaryAssists': 'Secondary Assists',
    'I_F_shotsOnGoal': 'Shots On Goal',
    'I_F_missedShots': 'Missed Shots',
    'I_F_blockedShotAttempts': 'Blocked Shot Attempts',
    'I_F_shotAttempts': 'Shot Attempts',
    'I_F_points': 'Points',
    'I_F_goals': 'Goals',
    'I_F_rebounds': 'Rebounds',
    'I_F_reboundGoals': 'Rebound Goals',
    'I_F_freeze': 'Freezes',
    'I_F_playStopped': 'Play Stopped',
    'I_F_playContinuedInZone': 'Play Continued In Zone',
    'I_F_playContinuedOutsideZone': 'Play Continued Outside Zone',
    'I_F_savedShotsOnGoal': 'Saved - Shots On Goal',
    'I_F_savedUnblockedShotAttempts': 'Saved - Unblocked Shot Attempts',
    'penalties': '# Of Penalties',
    'I_F_penalityMinutes': 'Penalty Minutes',
    'I_F_faceOffsWon': 'Face Offs Won',
    'I_F_hits': 'Hits',
    'I_F_takeaways': 'Takeaways',
    'I_F_giveaways': 'Giveaways',
    'I_F_lowDangerShots': 'Low Danger Shots',
    'I_F_mediumDangerShots': 'Medium Danger Shots',
    'I_F_highDangerShots': 'High Danger Shots',
    'I_F_lowDangerxGoals': 'xGoals - Low Danger',
    'I_F_mediumDangerxGoals': 'xGoals - Medium Danger',
    'I_F_highDangerxGoals': 'xGoals - High Danger',
    'I_F_lowDangerGoals': 'Goals - Low Danger',
    'I_F_mediumDangerGoals': 'Goals - Medium Danger',
    'I_F_highDangerGoals': 'Goals - High Danger',
    'I_F_scoreAdjustedShotsAttempts': 'Shot Attempts - Score Adjusted',
    'I_F_unblockedShotAttempts': 'Shot Attempts - Unblocked',
    'I_F_scoreAdjustedUnblockedShotAttempts': 'Shot Attempts - Unblocked + Score Adjusted',
    'I_F_dZoneGiveaways': 'D Zone Giveaways',
    'I_F_xGoalsFromxReboundsOfShots': 'xGoals - From xRebounds Of Shots',
    'I_F_xGoalsFromActualReboundsOfShots': 'xGoals - From Acutal Rebounds Of Shots',
    'I_F_reboundxGoals': 'Rebound xGoals',
    'I_F_xGoals_with_earned_rebounds': 'xGoals - w/ Earned Rebounds',
    'I_F_xGoals_with_earned_rebounds_scoreAdjusted': 'xGoals - w/ Earned Rebounds + Score Adjusted',
    'I_F_xGoals_with_earned_rebounds_scoreFlurryAdjusted': 'x Goals - x/ Earned Rebounds + Score Adjusted + Flurry Adjusted',
    'I_F_shifts': 'Shifts',
    'I_F_oZoneShiftStarts': 'Shift Starts - O Zone',
    'I_F_dZoneShiftStarts': 'Shift Starts - D Zone',
    'I_F_neutralZoneShiftStarts': 'Shift Starts - Nuetral Zone',
    'I_F_flyShiftStarts': 'Shift Starts - On The Fly',
    'I_F_oZoneShiftEnds': 'Shift Ends - O Zone',
    'I_F_dZoneShiftEnds': 'Shift Ends - D Zone',
    'I_F_neutralZoneShiftEnds': 'Shift Ends - Neutral Zone',
    'I_F_flyShiftEnds': 'Shift Ends - On The Fly',
    'faceoffsWon': 'FaceOffs Won - On Ice',
    'faceoffsLost': 'Faceoffs Lost - On Ice',
    'timeOnBench': 'Time On Bench (min)',
    'penalityMinutes': 'Penalty Minutes',
    'penalityMinutesDrawn': 'Penalty Minutes Drawn',
    'penaltiesDrawn': 'Penalties Drawn',
    'shotsBlockedByPlayer': 'Shots Blocked',
    'OnIce_F_xOnGoal': 'xShots On Goal - On Ice For',
    'OnIce_F_xGoals': 'xGoals - On Ice For',
    'OnIce_F_flurryAdjustedxGoals': 'xGoals - On Ice For - Flurry Adjusted',
    'OnIce_F_scoreVenueAdjustedxGoals': 'xGoals - On Ice For - Score Venue Adjusted',
    'OnIce_F_flurryScoreVenueAdjustedxGoals': 'xGoals - On Ice For - Score Venue Adjusted + Flurry Adjusted',
    'OnIce_F_shotsOnGoal': 'Shots On Goal - On Ice For',
    'OnIce_F_missedShots': 'Missed Shots - On Ice For',
    'OnIce_F_blockedShotAttempts': 'Blocked Shot Attempts - On Ice For',
    'OnIce_F_shotAttempts': 'Shot Attempts - On Ice For',
    'OnIce_F_goals': 'Goals - On Ice For',
    'OnIce_F_rebounds': 'Rebounds - On Ice For',
    'OnIce_F_reboundGoals': 'Rebound Goals - On Ice For',
    'OnIce_F_lowDangerShots': 'Shots - On Ice For - Low Danger',
    'OnIce_F_mediumDangerShots': 'Shots - On Ice For - Medium Danger',
    'OnIce_F_highDangerShots': 'Shots - On Ice For - High Danger',
    'OnIce_F_lowDangerxGoals': 'xGoals - On Ice For - Low Danger',
    'OnIce_F_mediumDangerxGoals': 'xGoals - On Ice For - Medium Danger',
    'OnIce_F_highDangerxGoals': 'xGoals - On Ice For - High Danger',
    'OnIce_F_lowDangerGoals': 'Goals - On Ice For - Low Danger',
    'OnIce_F_mediumDangerGoals': 'Goals - On Ice For - Medium Danger',
    'OnIce_F_highDangerGoals': 'Goals - On Ice For - High Danger',
    'OnIce_F_scoreAdjustedShotsAttempts': 'Shot Attempts - On Ice For - Score Adjusted',
    'OnIce_F_unblockedShotAttempts': 'Shot Attempts - On Ice For - Unblocked',
    'OnIce_F_scoreAdjustedUnblockedShotAttempts': 'Shot Attempts - On Ice For - Unblocked + Score Adjusted',
    'OnIce_F_xGoalsFromxReboundsOfShots': 'xGoals - On Ice For - From xRebounds Of Shots',
    'OnIce_F_xGoalsFromActualReboundsOfShots': 'xGoals - On Ice For - From Acutal Rebounds Of Shots',
    'OnIce_F_reboundxGoals': 'xRebound Goals - On Ice For',
    'OnIce_F_xGoals_with_earned_rebounds': 'xRebound Goals - On Ice For',
    'OnIce_F_xGoals_with_earned_rebounds_scoreAdjusted': 'xGoals - On Ice For - w/ Earned Rebounds + Score Adjusted',
    'OnIce_F_xGoals_with_earned_rebounds_scoreFlurryAdjusted': 'xGoals - On Ice For - with Earned Rebounds + Score Adjusted + Flurry Adjusted',
    'OnIce_A_xOnGoal': 'xShots On Goal Against - On Ice For',
    'OnIce_A_xGoals': 'xGoals Against - On Ice For',
    'OnIce_A_flurryAdjustedxGoals': 'xGoals Against - On Ice For - Flurry Adjusted',
    'OnIce_A_scoreVenueAdjustedxGoals': 'xGoals Against - On Ice For - Score Adjusted + Venue Adjusted',
    'OnIce_A_flurryScoreVenueAdjustedxGoals': 'xGoals Against - On Ice For - Score Adjusted + Venue Adjusted + Flurry Adjusted',
    'OnIce_A_shotsOnGoal': 'Shots On Goal Against - On Ice For',
    'OnIce_A_missedShots': 'Missed Shots Against - On Ice For',
    'OnIce_A_blockedShotAttempts': 'Blocked Shot Attempts Against - On Ice For',
    'OnIce_A_shotAttempts': 'Shot Attempts Against - On Ice For',
    'OnIce_A_goals': 'Goals Against - On Ice For',
    'OnIce_A_rebounds': 'Rebounds Against - On Ice For',
    'OnIce_A_reboundGoals': 'Rebound Goals Against - On Ice For',
    'OnIce_A_lowDangerShots': 'Shots Against - On Ice For - Low Danger',
    'OnIce_A_mediumDangerShots': 'Shots Against - On Ice For - Medium Danger',
    'OnIce_A_highDangerShots': 'Shots Against - On Ice For - High Danger',
    'OnIce_A_lowDangerxGoals': 'xGoals Against - On Ice For - Low Danger',
    'OnIce_A_mediumDangerxGoals': 'xGoals Against - On Ice For - Medium Danger',
    'OnIce_A_highDangerxGoals': 'xGoals Against - On Ice For - High Danger',
    'OnIce_A_lowDangerGoals': 'Goals Against - On Ice For - Low Danger',
    'OnIce_A_mediumDangerGoals': 'Goals Against - On Ice For - Medium Danger',
    'OnIce_A_highDangerGoals': 'Goals Against - On Ice For - High Danger',
    'OnIce_A_scoreAdjustedShotsAttempts': 'Shot Attempts Against - On ice For - Score Adjusted',
    'OnIce_A_unblockedShotAttempts': 'Shot Attempts Against - On Ice For - Unblocked',
    'OnIce_A_scoreAdjustedUnblockedShotAttempts': 'Shot Attempts Against - On Ice For - Unblocked + Score Adjusted',
    'OnIce_A_xGoalsFromxReboundsOfShots': 'xRebound Goals Against - On Ice For - From xRebounds Of Shots Against',
    'OnIce_A_xGoalsFromActualReboundsOfShots': 'xRebound Goals - On Ice For - From Actual Rebounds Of Shots Against',
    'OnIce_A_reboundxGoals': 'xRebound Goals Against - On Ice For',
    'OnIce_A_xGoals_with_earned_rebounds': 'xRebound Goals Against - On Ice For - w/ Earned Rebounds',
    'OnIce_A_xGoals_with_earned_rebounds_scoreAdjusted': 'xGoals - On Ice For - w/ Earned Rebounds + Score Adjusted',
    'OnIce_A_xGoals_with_earned_rebounds_scoreFlurryAdjusted': 'xGoals w/ Earned Rebounds - On Ice For - Score Flurry Adjusted',
    'OffIce_F_xGoals': 'xGoals For - Off Ice For',
    'OffIce_A_xGoals': 'xGoals Against - Off Ice For',
    'OffIce_F_shotAttempts': 'Shot Attempts - Off Ice For',
    'OffIce_A_shotAttempts': 'Shot Attempts - Off Ice Against',
    'xGoalsForAfterShifts': 'xGoals For - After Shifts',
    'xGoalsAgainstAfterShifts': 'xGoals Against - After Shifts',
    'corsiForAfterShifts': ' Corsi For - After Shifts',
    'corsiAgainstAfterShifts': ' Corsi Against - After Shifts',
    'fenwickForAfterShifts': 'Fenwick For - After Shifts',
    'fenwickAgainstAfterShifts': 'Fenwick Against - After Shifts'
}

# List to map the main color for each NFL team
teams_color = {
    'ANA': '#F47A38', 
    'ARI': '#8C2633',
    'BOS': '#FFB81C', 
    'BUF': '#003087', 
    'CGY': '#D2001C', 
    'CAR': '#CE1126', 
    'CHI': '#CF0A2C', 
    'COL': '#6F263D', 
    'CBJ': '#002654', 
    'DAL': '#006847', 
    'DET': '#CE1126', 
    'EDM': '#041E42', 
    'FLA': '#041E42', 
    'LAK': '#111111', 
    'MIN': '#154734', 
    'MTL': '#AF1E2D', 
    'NSH': '#FFB81C', 
    'NJD': '#CE1126', 
    'NYI': '#00539B', 
    'NYR': '#0038A8', 
    'OTT': '#DA1A32', 
    'PHI': '#F74902', 
    'PIT': '#FCB514', 
    'STL': '#002F87', 
    'SJS': '#006D75', 
    'SEA': '#001628', 
    'TBL': '#002868', 
    'TOR': '#00205B', 
    'VAN': '#00205B', 
    'VGK': '#B4975A', 
    'WSH': '#C8102E', 
    'WPG': '#041E42'
}